config/routes.rb
Rails.application.routes.draw do
  mount EpicEditor::Engine => "/"
  resources :wikis do
    member do
      post :add_collaborator
      delete :remove_collaborator
    end
  end
  devise_for :users
  resources :charges, only: [:new, :create]
  put 'users/downgrade', to: 'charges#downgrade', as: :downgrade
  root 'welcome#index'
end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :collaborator, class_name: "User"
  belongs_to :wiki
end

app/models/premium.rb
class Premium
# Stripe card processing fields for charges_controller.rb
# Access via "Premioum::NAME"
  AMOUNT = 1500
  DESCRIPTION = "Blocipedia Premium for #{current_user.email}"
  CURRENCY = "usd"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :wikis
  has_many :collaborations

  after_initialize :init

  enum role: [:standard, :premium, :admin]

  def init
    self.role ||= 'standard'
  end

  def upgrade
    self.premium! ? true : false
  end

  def downgrade
    self.standard! ? true : false
  end


end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  belongs_to :user
  has_many :collaborations
  has_many :collaborators, through: :collaborations

  def make_public
    self.private = false
    self.save
  end

  def add_collab(collaborator_id)
    collab = Collaboration.new(collaborator_id: collaborator_id, wiki: self)
    collab.save
  end

  def remove_collab(collaborator_id)
    collab = Collaboration.where(collaborator_id: collaborator_id, wiki: self)
    Collaboration.destroy(collab[0].id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  include Plans::Premium
  before_action :authenticate_user!, only: [:new, :create, :downgrade]

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: charge_description,
      # the following action is not passing spec tests, undefined method `description' for Premium:Module
      # description: Premium::description(current_user.email),
      amount: AMOUNT
    }
  end

  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      # this is the Stripe customer object ID
      customer: customer.id,
      # must be in cents
      amount: AMOUNT,
      description: charge_description,
      # the following action is not passing spec tests, undefined method `description' for Premium:Module
      # description: Premium::description(current_user.email),
      currency: CURRENCY
    )

    # change user to premium
    if current_user.upgrade
      flash[:notice] = "Welcome to Premium status. Payment successful #{current_user.email}. Thank you."
    else
      flash[:notice] = "Payment received but we ran into an error with our database. Please contact support."
    end
    redirect_to wikis_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  def downgrade
    if current_user.downgrade
      current_user.wikis.each do |wiki|
        wiki.make_public
      end

      flash[:notice] = "Account downgraded, #{current_user.email}. Thank you."
    else
      flash[:notice] = "Database error occurred. Please contact support."
    end
    redirect_to wikis_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to edit_user_registration_path
  end
end

app/controllers/concerns/plans.rb
module Plans
  module Premium
  # Stripe card processing fields for charges_controller.rb
  # Access via "Premioum::NAME"
    AMOUNT = 1500
    CURRENCY = "usd"

    def charge_description
      "Premium Upgrade for #{current_user.email}"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]
  before_action :ready_wiki, only: [:show, :edit, :update, :destroy, :add_collaborator, :remove_collaborator]

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    if @wiki.private && current_user.standard?
      flash.now[:alert] = "Free users can't make private wikis :("
      render :index
    end
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(wiki_params.merge(user_id: current_user.id))
    #@wiki.slug = @wiki.friendly_id
    if @wiki.private && current_user.standard?
      flash.now[:alert] = "Free users can't make private wikis :("
      render :new
    else
      if @wiki.save
        flash[:notice] = "Wiki saved"
        redirect_to @wiki
      else
        flash.now[:alert] = "Error saving your wiki occurred! Try again"
        render :new
      end
    end
  end

  def edit
    @users =  User.all
  end

  def update
    @wiki.update_attributes(wiki_params)

    if @wiki.private && current_user.standard?
      flash.now[:alert] = "Free users can't make private wikis :("
      render :edit
    else
      if @wiki.save
        flash[:notice] = "Wiki was updated"
        redirect_to @wiki
      else
        flash.now[:alert] = "Error saving your wiki - plz try again"
        render :edit
      end
    end
  end

  def destroy
    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully"
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki"
      render :show
    end
  end

  def add_collaborator
    @wiki.add_collab(params[:collaborator_id])
    redirect_to edit_wiki_path(@wiki)
  end

  def remove_collaborator
    @wiki.remove_collab(params[:collaborator_id])
    redirect_to edit_wiki_path(@wiki)
  end


  private
  def ready_wiki
    @wiki = Wiki.find(params[:id])
  end

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action"
    redirect_to wikis_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def markdowner(input)
    renderer = Redcarpet::Render::HTML.new(safe_links_only: true, hard_wrap: true)
    markdown = Redcarpet::Markdown.new(renderer, fenced_code_blocks: true, autolink: true, underline: true, highlight: true)
    markdown.render(input)
  end
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Upgrade to Premium</h4>
  <h5>Benefits include:</h5>
  <ul>
    <li>Create your own Private content</li>
    <li>Access to Private content</li>
    <li>Create and control custom edit lists</li>
    <li>Bragging rights</li>
  </ul>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js"
   data-key="<%= @stripe_btn_data[:key] %>"
   data-amount="<%= @stripe_btn_data[:amount] %>"
   data-description="<%= @stripe_btn_data[:description] %>">
  </script>
<% end %>
<p>
  <small>By purchasing an upgrade, you agree to the following terms and conditions. All payments are non-refundable. We are not responsible for literally anything on this website. You agree to hold us harmless from any damages, real or imagined, incurred in any way through this site. You agree to only say nice things about us. You understand that use of our site is at our discretion and can be cancelled or revoked at any time. You agree that any disputes with us for anything will be handled by a mediator of our choosing in a location of our choosing. Mediation costs will be born by the user.</small>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Blocipedia</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "Blocipedia", root_path %></h1>
        </li>
      </ul>

      <section class="top-bar-section">
        <ul class="right">
          <% if user_signed_in? %>
            <li><%= link_to "Edit #{current_user.email}", edit_user_registration_path %></li>
            <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </section>
    </nav>

    <%if flash[:notice] %>
      <div data-alert class="alert-box success">
        <a href="#" class="close">&times;</a>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:alert] %>
      <div data-alert class="alert-box alert">
        <a href="#" class="close">&times;</a>
        <%= flash.now[:alert] %>
      </div>
    <% elsif flash[:alert] %>
      <div data-alert class="alert-box warning">
        <a href"#" class="close">&times;</a>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <div class="row">
      <div class="12-large column">
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.haml
.row.banner
  .small-12.columns.small-centered
    %h1 Blocipedia: Social, Markdown Wikis
.row
  .row
    .small-6.column.small-centered.box#top-box
      %h4 Create and share Markdown Wikis
  .row
    .small-6.columns.small-centered.box#bottom-box
      - if user_signed_in?
        %p Hello, #{current_user.email}!
      - else
        =link_to "Sign up", new_user_registration_path, class: "button success huge"
.row
  .small-6.columns.small-centered.box#wiki-box
    %h2
      =link_to 'Clicky for Wikis', wikis_path

- if current_user == nil
  .row
    .small-2.columns
      %p
    .small-3.columns.box#left-box
      %h4 Create as many public wikis as you want
      =link_to 'Create Free Plan', new_user_registration_path, class: 'button'
    .small-2.columns
      %p
    .small-3.columns.box#right-box
      %h4 Create private wikis!
      =link_to 'Premium Plan $15', new_charge_path, class: 'button'
    .small-2.columns
      %p
- elsif current_user && current_user.standard?
  .row
    .small-4.columns
      %p
    .small-4.columns.box#right-box
      %h4 Create private wikis!
      =link_to 'Premium Plan $15', new_charge_path, class: 'button'
    .small-4.columns
      %p
- elsif current_user && current_user.admin?
  .row
    .small-4.columns
      %p
    .small-4.columns
      %h4 Gutentag, Herr Administrator
    .small-4.columns
      %p

app/views/welcome/index.html.erb
<h1>Welcome to Blocipedia</h1>

app/views/wikis/_form.html.haml
.row
  = form_for wiki do |f|
    .row
      = f.label :title
      = f.text_field :title, placeholder: "The Wiki Title"
    .row
      = f.label :body
      #epiceditor
        = f.text_area :body, placeholder: "The wiki content goes here.", id: "content-input"
    - if current_user.admin? || current_user.premium?
      .row
        = f.label :private
        = f.check_box :private
    .row
      = f.submit "Save", class: "button info"
      = link_to "Cancel", wikis_path, class: "button"
:javascript
  $(document).ready( function() {
    var options = { container: 'epiceditor'
          , basePath: '/app/assets'
          , textarea: 'content-input'
          , clientSideStorage: true
          , localStorageName: 'epiceditor'
          , useNativeFullscreen: true
          , file: { name: null
          , defaultContent: ''
            , autoSave: 100 // Set to false for no auto saving
            }
          , theme: { base: '/epiceditor.css'
            , preview: '/github.css'
            , editor: '/epic-style.css'
            }
          , focusOnLoad: false
          , shortcut: { modifier: 18 // alt keycode
            , fullscreen: 70 // f keycode
            , preview: 80 // p keycode
            }
          , string: { togglePreview: 'Toggle Preview Mode'
            , toggleEdit: 'Toggle Edit Mode'
            , toggleFullscreen: 'Enter Fullscreen'
            }
          , parser: typeof marked == 'function' ? marked : null
          , autogrow: false
          , button: { fullscreen: true
            , preview: true
            , bar: true
            }
          }
  var editor = new EpicEditor(options).load();
  });

app/views/wikis/edit.html.haml
.row
  %h1 Edit Wiki
=render partial: "form", locals: {wiki: @wiki}
- if @wiki.private
  .row
    %h4 Current Collaborators
    - @wiki.collaborators.each do |collaborator|
      .row
        = link_to "remove", remove_collaborator_wiki_path(wiki_id: @wiki.id, collaborator_id: collaborator.id), method: :delete, class: "button tiny alert"
        = collaborator.email
  .row
    %h4 Add Collaborators
    - @users.each do |user|
      - unless @wiki.collaborators.include? user
        .row
          = link_to "add", add_collaborator_wiki_path(wiki_id: @wiki.id, collaborator_id: user.id), method: :post, class: "button tiny success"
          = user.email

app/views/wikis/index.html.haml
.row
  %h1#title Public Wikis
- @wikis.each do |wiki|
  .row
    .small-10.columns
      =link_to wiki.title, wiki, class: "wiki-title"
    - if current_user && policy(wiki).edit?
      .small-1.column
        =link_to "Edit", edit_wiki_path(wiki), class:"button tiny info"
      - if current_user && policy(wiki).destroy?
        .small-1.column
          =link_to "Delete", wiki, method: :delete, class:"button tiny alert", data: {confirm: "are you sure? delete is forever."}
.row
  = link_to 'New Wiki', new_wiki_path, class: "button"

app/views/wikis/new.html.haml
.row
  %h1.title New Wiki
=render partial: "form", locals: {wiki: @wiki}

app/views/wikis/show.html.haml
.row
  .row
    %h1
      = @wiki.title
  .row
    = markdowner(@wiki.body).html_safe
  .row
    .small-2.columns
      %h5
        - if @wiki.private
          Private Wiki
        - else
          Public Wiki
    .small-10.columns
      %h5 Author: #{@wiki.user.email}
  .row
    = link_to 'Back', wikis_path, class: "button"
    - if current_user && policy(@wiki).edit?
      = link_to 'Edit', edit_wiki_path(@wiki), class: "button info"
    - if current_user && policy(@wiki).destroy?
      = link_to 'Delete', @wiki, method: :delete, class: "button alert", data: {confirm: "are you sure? delete is forever"}